name: CI

on:
  pull_request:
    paths:
      - "!**/README.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Format
        run: bun run format

      - name: Run build
        run: bun run build

      - name: Run tests
        run: bun run test
